name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - 3.7
          - 3.8

    steps:
      - uses: actions/checkout@master

      # C CHECKS

      - name: Install Libcheck on ${{ matrix.os }}
        if: ${{ matrix.os }} != "windows-latest" # FIXME
        env:
          OS: ${{ matrix.os }}
        run: |
          sh cmake/install_libcheck.sh

      - name: Build macro and run tests
        if: ${{ matrix.os }} != "windows-latest"
        run: |
          cmake -DMACRO_BUILD_TESTS=ON .
          make
          ./tests/macro_test

      # PYTHON CHECKS

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build python macro
        run: |
          cd bindings/python
          make uninstall
          make install
          python -m pip install --upgrade pytest
          cd ../../

      - name: Run tests
        run: |
          pytest

      - name: Run benchmarks
        run: |
          python benchmarks/benchmarks_builder.py